### ISSUE TITLE
Finish cell interactions

### ISSUE THREAD

**Issue by ZoeLocke** [OzLocke/ThePrisonTextAdventure#9]
## Task

Now that the structure of the code is complete we just need to build the game, to start with we should finish the cell, and all interactions involved with it.
## Areas and their interactions
- [x] Cell
  - [x] First visit
  - [x] Return
  - [x] Combining the sheet and the broken glass
- [x] Bed
  - [x] First visit without the broken glass
  - [x] First visit with the broken glass
  - [x] Taking the sheet
  - [x] Stabbing the bed with the broken glass
  - [x] Stabbing the bed with the shiv
  - [x] Returning with the sheet & with the broken glass
  - [x] Returning without the sheet & with the broken glass
  - [x] Returning without the sheet & without the broken glass
  - [x] Returning with the sheet & without the broken glass
  - [x] Returning with the shiv
- [x] Mirror
  - [x] First visit
  - [x] Returning with the broken glass
  - [x] Returning without the broken glass
  - [x] Taking the broken glass
- [x] Door
  - [x] First visit
  - [x] Returning
  - [x] Using fists on the door
  - [x] Using the broken glass on the door
  - [x] Using the shiv on the door
  - [x] Pushing the door
  - [x] Yelling through the door
  - [x] Trying the lock
- [x] Corridor
  - [x] Attacking the guard with the shiv or broken glass
  - [x] Attacking the guard without a weapon
  - [x] Talking to the guard when he's facing you
  - [x] Talking to the guard when he's facing away from you
  - [x] Sneaking passed the guard
  - [x] Running passed the guard

**Comment by ZoeLocke** [comment]
Done
